---
- name: Install Nginx
  hosts: hosts
  become: yes
  tasks:
    - name: Install Nginx package
      package:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
