---
- name: Uninstall Nginx
  hosts: ansible-hosts
  become: yes
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped

    - name: Uninstall Nginx package
      package:
        name: nginx
        state: absent
