---
- name: variables
  hosts: localhost
  vars:
    Course: "Jenkins"
    Trainer: "Sivakumar"
    Duration: "150hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
       msg: "Hi, we are learning {{Course}} Ansible from {{Trainer}} Sivakumar, {{Duration}} is 120hrs"