---
- name: variables
  hosts: localhost
  vars_files:
  - vars-file.yaml
  tasks:
  - name: print information
    ansible.builtin.debug:
       msg: "Hi, we are learning {{Course}} from {{Trainer}} and duration is {{Duration}} and fees is {{Fees}}"