---
- name: variables
  hosts: ansible-hosts
  vars_files:
  - vars-file.yaml
  tasks:
  - name: print information
    ansible.builtin.debug:
       msg: "execute playbook {{ENV}} for {{Project}} and {{type}}